---

- name: clone couchpotato
  git:
    repo: https://github.com/CouchPotato/CouchPotatoServer.git
    dest: /opt/CouchPotatoServer
    update: no
  become: yes
  notify: restart_couchpotato

- name: fix perms
  file:
    path: /opt/CouchPotatoServer
    state: directory
    recurse: yes
    owner: "{{ couchpotato_user }}"
  become: yes
